"""Classify content as image, text, or binary.

The server does not decode pixels. It checks image containers within fixed
bounds; an image signature that fails validation becomes opaque binary content
and is never previewed. Text is validated as UTF-8; everything else is also
treated as opaque binary content.
"""
from __future__ import annotations

import re
from dataclasses import dataclass

from .config import DEFAULT_MAX_IMAGE_PIXELS, LimitsConfig
from .images import (
    FORMATS,
    InvalidImageError,
    inspect_image,
    mime_for,
)

_DEFAULT_LIMITS = LimitsConfig()

# Declared text types -> extension (paste preserves clipboard identity).
TEXT_MIMES: dict[str, str] = {
    "text/plain": ".txt",
    "text/markdown": ".md",
    "text/html": ".html",
    "text/css": ".css",
    "text/javascript": ".js",
    "application/json": ".json",
    "application/xml": ".xml",
    "text/csv": ".csv",
    "application/x-yaml": ".yaml",
    "application/x-sh": ".sh",
    "text/x-python": ".py",
    "text/x-shellscript": ".sh",
}
DEFAULT_TEXT_EXT = ".txt"
DEFAULT_BINARY_EXT = ".bin"

_SAFE_EXT_RE = re.compile(r"^[A-Za-z0-9]{1,10}$")

_SIGNATURES = (
    (b"\x89PNG\r\n\x1a\n", "png"),
    (b"\xff\xd8\xff", "jpeg"),
    (b"RIFF", "webp"),
)


@dataclass(frozen=True)
class ContentInfo:
    kind: str  # "image" | "text" | "binary"
    ext: str  # Extension with a dot, generated by the server.
    mime: str  # MIME type served to the client.
    width: int | None = None
    height: int | None = None
    fmt: str | None = None  # FORMATS key for images.


def _is_text(data: bytes) -> bool:
    if b"\x00" in data:
        return False
    try:
        data.decode("utf-8")
    except UnicodeDecodeError:
        return False
    return True


def safe_extension(name: str | None) -> str | None:
    """Return a sanitized original extension (drop): [A-Za-z0-9]{1,10}."""
    if not name:
        return None
    # Upload names use the same separator-independent syntax on every host.
    basename = name.replace("\\", "/").rsplit("/", 1)[-1]
    if basename.startswith(".."):
        return None
    dot = basename.rfind(".")
    if dot <= 0:
        return None
    ext = basename[dot + 1:]
    ext = re.sub(r"[^A-Za-z0-9]", "", ext)
    if not _SAFE_EXT_RE.fullmatch(ext):
        return None
    return "." + ext.lower()


def classify(
    data: bytes,
    declared_mime: str | None,
    filename_hint: str | None = None,
    *,
    max_pixels: int | None = DEFAULT_MAX_IMAGE_PIXELS,
    max_dimension: int | None = _DEFAULT_LIMITS.max_image_dimension,
    max_raw_bytes: int | None = _DEFAULT_LIMITS.max_image_raw_bytes,
    max_png_chunks: int | None = _DEFAULT_LIMITS.max_png_chunks,
    max_jpeg_segments: int | None = _DEFAULT_LIMITS.max_jpeg_segments,
    max_webp_chunks: int | None = _DEFAULT_LIMITS.max_webp_chunks,
) -> ContentInfo:
    """Classify content: image signature, UTF-8 text, or binary fallback."""
    # 1. Image: the content signature is authoritative.
    for sig, fmt in _SIGNATURES:
        if data.startswith(sig):
            try:
                info = inspect_image(
                    data,
                    max_pixels=max_pixels,
                    max_dimension=max_dimension,
                    max_raw_bytes=max_raw_bytes,
                    max_png_chunks=max_png_chunks,
                    max_jpeg_segments=max_jpeg_segments,
                    max_webp_chunks=max_webp_chunks,
                )
            except InvalidImageError:
                # An image-looking upload that cannot pass the bounded
                # structural check is still safe to retain as an attachment.
                image_ext = safe_extension(filename_hint) or ".bin"
                return ContentInfo(
                    kind="binary",
                    ext=image_ext,
                    mime="application/octet-stream",
                )
            else:
                return ContentInfo(
                    kind="image",
                    ext=FORMATS[info.fmt][0],
                    mime=mime_for(info.fmt),
                    width=info.width,
                    height=info.height,
                    fmt=info.fmt,
                )
    # 2. Text: declared text OR valid UTF-8 content.
    declared = (declared_mime or "").split(";")[0].strip().lower()
    if declared.startswith("text/") or declared in (
        "application/json",
        "application/xml",
        "application/x-yaml",
    ):
        if _is_text(data):
            ext = TEXT_MIMES.get(declared, DEFAULT_TEXT_EXT)
            return ContentInfo(kind="text", ext=ext, mime=declared or "text/plain")
    if _is_text(data):
        return ContentInfo(kind="text", ext=DEFAULT_TEXT_EXT, mime="text/plain")
    # 3. Binary: original extension for drops, otherwise .bin.
    ext = safe_extension(filename_hint) or DEFAULT_BINARY_EXT
    return ContentInfo(kind="binary", ext=ext, mime="application/octet-stream")
